[config]
schemaVersion = "0.1.2"

[package]
namespace = "Binbin"
name = "Albedo"
versionNumber = "0.1.2"
description = "Hero Mod for Albedo, the Overseer. A faithful and loyal warrior, serving Ainz Ooal Gown. She is extremely protective and willing to take hits for her allies."
websiteUrl = "https://github.com/binbinmods/Albedo"
containsNsfwContent = false

[package.dependencies]
meds-Obeliskial_Essentials = "1.5.1"
meds-Obeliskial_Content = "1.5.6"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./Albedo"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]


